platform :ios, '15.0'

target 'App' do
  use_frameworks!  # if you need dynamic frameworks
  use_modular_headers!

  # Pods for Capacitor
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'

  # Add your other plugins here, for example:
  # pod 'Firebase/Core'
  # pod 'Firebase/Auth'

end